### ISSUE TITLE
Confusion with preprocessing pipeline

### ISSUE THREAD

**Issue by tjtanaa** [tyagi-iiitv/PointPillars#26]
I have question regarding to your preprocessing pipeline. I have tried to visualize and make sense of your coordinate system and preprocessing pipeline; however, I still could grasp it.

1) Could I know why would you want to minus -pi/2 when the range of the label is already within the range [-pi, pi]? The following is the snippet of code from `processors.py` that illustrate that.

```

    @staticmethod
    def transform_labels_into_lidar_coordinates(labels: List[Label3D], R: np.ndarray, t: np.ndarray):
        transformed = []
        for label in labels:
            label.centroid = label.centroid @ np.linalg.inv(R).T - t
            label.dimension = label.dimension[[2, 1, 0]] # h w l => l ,w ,h
            label.yaw -= np.pi / 2
            while label.yaw < -np.pi:
                 print("smaller than -pi")
                 label.yaw += (np.pi * 2)
            while label.yaw > np.pi:
                 print("larger than pi")
                 label.yaw -= (np.pi * 2)
            transformed.append(label)
        return labels
```

2) Moreover, which axes do the width and length correspond to in your coordinate system? Is it w for x axis and l for y axis?
3) Do I need to offset the z height by height/2 to get the true center of the bounding box in your coordinate system?

**Comment by dvrohan** [comment]
Also the function returns labels. What is the use of transformed list?

**Comment by Manueljohnson063** [comment]
@tjtanaa @dvrohan @kvssraviteja 
2021-03-07 17:54:35.720682: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-03-07 17:54:37.690026: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-03-07 17:54:38.183182: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
Scene 1: Box predictions with occupancy > occ_thr: 0
Traceback (most recent call last):
File "point_pillars_prediction.py", line 43, in
nms_boxes = rotational_nms(set_boxes, confidences, occ_threshold=0.7, nms_iou_thr=0.5)
File "/content/drive/MyDrive/PointPillars/inference_utils.py", line 41, in rotational_nms
assert (isinstance(set_boxes[0][0][0][0], float) or isinstance(set_boxes[0][0][0][0], int)) and
IndexError: list index out of range
-------------------------------------------------------------------
I put for files in testing folder(4-velodyne,4-calib)
000000,00001,000002,00003
Error is poping out please help !!!!!!!!!!!!!!!!!!!!

**Comment by viplix3** [comment]
I also have the same confusion as @tjtanaa.
