### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by sivaprasadraju** [tyagi-iiitv/PointPillars#30]
@tyagi-iiitv Did your pretrained model reached the performance according to PointPillar paper?

**Comment by han1366** [comment]
I think not. I find that the code is not very similar  to paper.The paper describes 9 features per point,but this code only define 7 features.

**Comment by Manueljohnson063** [comment]
@han1366 @sivaprasadraju 
2021-03-07 17:54:35.720682: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-03-07 17:54:37.690026: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-03-07 17:54:38.183182: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
Scene 1: Box predictions with occupancy > occ_thr:  0
Traceback (most recent call last):
  File "point_pillars_prediction.py", line 43, in <module>
    nms_boxes = rotational_nms(set_boxes, confidences, occ_threshold=0.7, nms_iou_thr=0.5)
  File "/content/drive/MyDrive/PointPillars/inference_utils.py", line 41, in rotational_nms
    assert (isinstance(set_boxes[0][0][0][0], float) or isinstance(set_boxes[0][0][0][0], int)) and \
IndexError: list index out of range

------------------------------
I put for files in testing folder(4-velodyne,4-calib)
000000,00001,000002,00003
Error is poping out please help !!!!!!!!!!!!!!!!!!!!

**Comment by han1366** [comment]
> @han1366 @sivaprasadraju
> 2021-03-07 17:54:35.720682: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
> 2021-03-07 17:54:37.690026: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
> 2021-03-07 17:54:38.183182: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
> Scene 1: Box predictions with occupancy > occ_thr: 0
> Traceback (most recent call last):
> File "point_pillars_prediction.py", line 43, in
> nms_boxes = rotational_nms(set_boxes, confidences, occ_threshold=0.7, nms_iou_thr=0.5)
> File "/content/drive/MyDrive/PointPillars/inference_utils.py", line 41, in rotational_nms
> assert (isinstance(set_boxes[0][0][0][0], float) or isinstance(set_boxes[0][0][0][0], int)) and
> IndexError: list index out of range
> 
> I put for files in testing folder(4-velodyne,4-calib)
> 000000,00001,000002,00003
> Error is poping out please help !!!!!!!!!!!!!!!!!!!!

I can't run this code, so I think you can try second.pytorch.That code run easily.

**Comment by tuan97anton** [comment]
@han1366  
Could you share the repo git of  second.pytorch ?

**Comment by eddydw** [comment]
[@tyagi-iiitv] (https://github.com/tyagi-iiitv) :  The pre-trained model model.h5 is missing . Can you please put it on the git repo or provide a link that is not broken please?
thanks in advance
Eddy
