### ISSUE TITLE
Hai error pops out when i trained,please help

### ISSUE THREAD

**Issue by Manueljohnson063** [tyagi-iiitv/PointPillars#32]
Traceback (most recent call last):
  File "point_pillars_training_run.py", line 26, in <module>
    pillar_net.load_weights(os.path.join(MODEL_ROOT, "model.h5"))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2227, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './logs/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by dvrohan** [comment]
Same for me. How can we load weights before training the model?

**Comment by Manueljohnson063** [comment]
hai bro please comment pillar_net.load_weights(os.path.join(MODEL_ROOT, "model.h5")) this  then it wil be fine
