### ISSUE TITLE
Failed to find data adapter that can handle input: <class 'processors.SimpleDataGenerator'>, <class 'NoneType'>

### ISSUE THREAD

**Issue by Gurk97** [tyagi-iiitv/PointPillars#45]
Hi!

I have been trying to launch the "point_pillars_training_run.py" file using python 3.8 on cuda 11.6. I have followed the instructions strictly (I belive). Now i am using a conda enviroment but i recieve the same error while on an virtual enviroment. I download the KITTY files and unpack them in the given directory structure. And run the "python setup.py install" without any issues or warnings. 

i recieve the following problem when running "python point_pillars_training_run.py":

super(Adam, self).__init__(name, **kwargs)
Traceback (most recent call last):
  File "point_pillars_training_run.py", line 58, in <module>
    pillar_net.fit(training_gen,
  File "/home/gustavni/anaconda3/envs/py38/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/gustavni/anaconda3/envs/py38/lib/python3.8/site-packages/keras/engine/data_adapter.py", line 984, in select_data_adapter
    raise ValueError(
ValueError: Failed to find data adapter that can handle input: <class 'processors.SimpleDataGenerator'>, <class 'NoneType'>

Any tips on how to get the code running?

Kind regards

**Comment by EricCurl** [comment]
I overcame this issue, and I believe it was a simple fix. In the processors.py script, just change:

`from tensorflow.python.keras.utils.data_utils import Sequence` to
`from tensorflow.keras.utils import Sequence`
